### ISSUE TITLE
Appveyor file broke

### ISSUE THREAD

**Issue by Phundrak** [Phundrak/output-vt100-rs#4]
Appveyor apparently changed the way it works and the `appveyor.yml` file broke. I haven’t worked with Appveyor in a very long time, so I’m not sure how to fix this, PRs are more than welcome for this.

**Comment by nbouteme** [comment]
I forked the repo and [AppVeyor still works properly](https://ci.appveyor.com/project/nbouteme/output-vt100-rs/build/job/mlialkmyrc5esywt).
According to the log, it's trying to execute a curl command that's not in the `appveyor.yml` file.

```
curl -sSf -o rustup-init.exe https://win.rustup.rs/                          
```

instead of 
```
appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
```

The most likely explanation is that there's a hardcoded build script in your appveyor project configuration (Settings > Build in the control panel)

But the yml file is fine otherwise.

**Comment by Phundrak** [comment]
That’s weird. I reset the Appveyor project and it seems to be fixed indeed. Closing this issue.

--
Lucien “Phundrak” Cartier-Tilet

<https://phundrak.com> (Français)

<https://phundrak.com/en> (English)

Sent from GNU/Emacs
